### ISSUE TITLE
Unable to transcribe YouTube videos

### ISSUE THREAD

**Issue by mroswell** [zackees/transcribe-anything#12]
the usage example at https://pypi.org/project/transcribe-anything/ (and in this repo's README file) is:
```
transcribe_anything https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

When I run that, I get:
```
zsh: no matches found: https://www.youtube.com/watch?v=dQw4w9WgXcQ
```
same with any other YouTube video URLs.

(i am more successful with Rumble links.)

**Comment by zackees** [comment]
So by the looks of it you are using the Mac with the new zsh, which is getting confused by one of the characters. If you switch the bash shell it will just work fine.

The solution for the zsh is that instead of this:

```
transcribe_anything https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

You put the second argument in quotes:

```
transcribe_anything "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
```

**Comment by zackees** [comment]
Reopening — the workaround was given to @mroswell but the **docs were never updated**, so anyone on zsh hits exactly the same wall today (2026-06-07).

## What the user actually hit

```
zsh: no matches found: https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

This is zsh's globbing biting before the URL is ever handed to `transcribe-anything`. The `?` in `?v=…` is a single-character glob. zsh's default `NOMATCH` option (on by default; documented in `man zshoptions`) treats glob patterns that don't match any file as a hard error and refuses to invoke the command at all. The CLI never gets the URL — the shell stops short.

This is zsh-specific:

- bash → glob doesn't expand against URL → URL is passed through verbatim → works.
- zsh (default macOS shell since Catalina, 2019) → URL looks like a glob → `NOMATCH` error.
- fish → URL is passed through verbatim → works.

Workarounds (any one works):

- Quote the URL: `transcribe-anything "https://www.youtube.com/watch?v=dQw4w9WgXcQ"` — what the 2023 close suggested.
- Or `setopt +o nomatch` to silence globally.
- Or `noglob transcribe-anything https://…`.
- Or escape: `transcribe-anything https://www.youtube.com/watch\?v=dQw4w9WgXcQ`.

## Why this is still an open bug in 2026

The 2023 close told *that user* how to work around it but never propagated the fix to the docs. As of `main` today (`grep -n 'transcribe-anything https' README.md`):

| Line | Snippet |
|---|---|
| 119 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ --device mlx` |
| 160 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ` |
| 163 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ --device insane` |
| 166 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ --device insane-flash` |
| 169 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ --device mlx` |
| 555 | `transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ` |

PyPI's project page mirrors the README, so PyPI is also broken. Six examples × every new macOS user × every zsh user on Linux = a steady stream of "doesn't work" reports that all bottom out in this same shell-globbing footgun.

## Why "tell users to learn zsh" isn't the right close

- macOS shipped zsh as the default in 2019. The audience asking "transcribe me a YouTube link" is overwhelmingly *not* people who know what `NOMATCH` is.
- The MLX backend the project markets prominently is **macOS only**. Most MLX users are on zsh by default. The README's MLX example specifically is on line 119, with the URL unquoted.
- The fix is a one-character edit per example. Cost of fixing: minutes. Cost of not fixing: the bug recurs forever.

## Proposed fix (small, isolated PR)

Quote the URL in **every** CLI example in `README.md` that uses one. There are 7 invocations to touch (the 6 above plus line 664 in the daemon section). Python-API examples on lines 182 and 847 already pass the URL as a quoted string literal — no change there.

While we're in the README:

- Add a one-paragraph "Why does zsh complain?" callout in the Troubleshooting section so the search-engine result for `zsh no matches found transcribe_anything` lands on a real explanation. Mention the 4 workarounds.
- Mirror the quoting fix to any code path that prints a sample command back to the user (`--help` output, error messages). Grep finds none today (`grep -rn 'transcribe-anything http' src/`), so this is just precautionary auditing.

PyPI auto-pulls the README on the next release, so the docs fix also fixes the PyPI page.

## Acceptance criteria

- [ ] Every `transcribe-anything https://…` example in `README.md` quoted, including the line-119 MLX example, the line-555 basic-usage example, and the four backend-specific examples around lines 160–169.
- [ ] New "zsh: no matches found" entry under Troubleshooting with the 4 workarounds.
- [ ] PyPI long description reflects the quoted form on the next release (automatic via `setup.py`/`pyproject.toml` README ingestion).
- [ ] No regression: `grep -nE '^[^"#]*transcribe-anything https?://[^"]*$' README.md` returns empty.

## Decisions

- **Priority: P3** — not a code bug, but a discoverable UX bug whose cost is exactly the README diff. Cheap to fix; cheaper still to keep deferring → infinitely many user-hours wasted.
- **Quote, don't switch the example URL.** Reason: Rick Astley's video ID is universally recognizable and a meme. Replacing it with a less-evocative URL doesn't fix the bug; only the quotes do.
- **Don't change the CLI to detect this.** Reason: the CLI never runs — the shell stops before exec. There's nothing the program can do; this is purely a docs fix.
- **Reopen, don't file a new issue.** Reason: the title and reporter context are already correct. The original close just stopped one step short.

I'll happily do the README-quoting PR if you want — just say go.
